server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.100.21
      discovery:
        hostname: 192.168.100.21
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}
      port: 8500
