server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# consumer request microservice name
service-url:
  nacos-user-service: http://nacos-payment-provider
