server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          destination: studyExchange # define an useful exchange name
          content-type: application/json # define message type, if text, then set "text/plain"
          binder: defaultRabbit # define the specifical setup which message service should be binded

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: send-8801.com
    lease-renewal-interval-in-seconds: 2 # setup renewal interval(default 30s)
    lease-expiration-duration-in-seconds: 5 # if more than 5s then remove the instance(default 90s)
    prefer-ip-address: true # change the request address to ip
