server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # nacos service register address
        server-addr: localhost:8848
    sentinel:
      transport:
        # the default is 8719, if the port has been used, the port number will increse from 8719 until the port is available
        port: 8719
        # setup the Sentinel dashboard address
        dashboard: localhost:8080
        datasource:
          ds1:
            nacos:
              server-addr: localhost:8848
              dataId: cloudalibaba-sentinel-service
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"

