server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: http://192.168.100.21
      port: 8500
      discovery:
        hostname: 192.168.100.21
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

